import Link from 'next/link'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: '博客 - AI工具使用技巧与干货分享 | AI Tools',
  description: '分享AI工具使用技巧、文案写作方法、职场效率提升等实用干货文章。',
}

const posts = [
  {
    slug: 'json-csv-converter-guide',
    title: 'JSON转CSV教程：接口数据如何快速整理成表格',
    desc: '讲清楚 JSON 和 CSV 的使用区别、常见转换场景，以及如何把接口返回结果快速整理成 Excel 可读表格。',
    date: '2026-03-16',
    tag: '开发工具',
  },
  {
    slug: 'timestamp-converter-guide',
    title: '时间戳转换器使用技巧：秒级、毫秒级、日期时间一键互转',
    desc: '从接口调试到日志排错，讲清楚时间戳转换器的高频使用场景，以及秒级和毫秒级时间戳的区别。',
    date: '2026-03-16',
    tag: '开发工具',
  },
  {
    slug: 'hash-generator-guide',
    title: 'Hash生成器使用指南：在线生成 MD5、SHA-1、SHA-256、SHA-512',
    desc: '从基础概念到实际场景，带你快速上手在线 Hash 生成器，搞懂 MD5、SHA-1、SHA-256、SHA-512 的区别。',
    date: '2026-03-16',
    tag: '开发工具',
  },
  {
    slug: 'xiaohongshu-copywriting-tips',
    title: '2026小红书爆款文案怎么写？5个模板直接套用',
    desc: '总结小红书爆款笔记的文案规律，提供5个可直接套用的模板，配合AI文案生成器一键搞定。',
    date: '2026-02-25',
    tag: '文案技巧',
  },
  {
    slug: 'baby-naming-guide-2026',
    title: '2026宝宝起名大全：寓意好又好听的名字推荐',
    desc: '精选古典文雅、时尚现代、诗词意境等多种风格的宝宝名字，附寓意解析和起名技巧。',
    date: '2026-02-25',
    tag: '起名指南',
  },
  {
    slug: 'weekly-report-template',
    title: '周报不会写？6种万能模板让你5分钟搞定',
    desc: '程序员、产品经理、运营、销售等不同岗位的周报模板，再也不用为写周报发愁。',
    date: '2026-02-25',
    tag: '职场效率',
  },
  {
    slug: 'resume-writing-guide',
    title: '简历怎么写才能通过HR筛选？2026最新指南',
    desc: '从简历结构、内容优化到常见误区，手把手教你写出高通过率的简历。',
    date: '2026-02-25',
    tag: '求职指南',
  },
  {
    slug: 'wechat-moments-copywriting',
    title: '高级感朋友圈文案大全：100+精选文案随便发',
    desc: '旅行、美食、自拍、工作、心情等场景的朋友圈文案合集，文艺、搞笑、高冷风格任选。',
    date: '2026-02-25',
    tag: '文案合集',
  },
  {
    slug: 'business-email-writing',
    title: '商务邮件怎么写？模板+范文+注意事项全攻略',
    desc: '商务合作、求职应聘、离职申请等6种常见邮件的写法，附专业模板和范文。',
    date: '2026-02-25',
    tag: '职场技能',
  },
  {
    slug: 'developer-tools-2026',
    title: '2026年程序员必备的10个在线开发工具',
    desc: '精选10个免费在线开发者工具：JSON格式化、Base64编解码、正则表达式测试等，无需安装，打开即用。',
    date: '2026-02-25',
    tag: '开发工具',
  },
  {
    slug: 'password-security-guide',
    title: '如何生成安全的密码？2026密码安全指南',
    desc: '密码安全完全指南：为什么你的密码不安全？如何生成强密码？密码管理最佳实践。',
    date: '2026-02-25',
    tag: '安全指南',
  },
  {
    slug: 'json-formatter-guide',
    title: '在线JSON格式化工具使用指南：格式化、压缩、校验',
    desc: '详细介绍JSON格式化工具的使用方法，包括常见JSON错误排查，程序员必备技能。',
    date: '2026-02-25',
    tag: '开发工具',
  },
  {
    slug: 'qrcode-generator-guide',
    title: '二维码生成器使用指南：如何免费生成QR Code',
    desc: '免费在线二维码生成器教程，支持网址、文本、WiFi信息，自定义尺寸，一键下载。',
    date: '2026-02-25',
    tag: '实用工具',
  },
  {
    slug: 'css-units-guide',
    title: 'CSS中px、rem、em、vw有什么区别？前端单位完全指南',
    desc: '详解CSS各种单位的区别和使用场景，附在线转换工具，前端开发必读。',
    date: '2026-02-25',
    tag: '前端开发',
  },
  {
    slug: 'uuid-guide',
    title: '什么是UUID？UUID v4生成原理与使用场景',
    desc: '详解UUID的概念、版本区别、v4生成原理，以及在数据库和分布式系统中的应用。',
    date: '2026-02-25',
    tag: '开发知识',
  },
  {
    slug: 'cron-expression-guide',
    title: 'Cron表达式详解：Linux定时任务完全指南',
    desc: '详解Cron表达式语法、常用示例，从入门到精通Linux定时任务配置。',
    date: '2026-02-25',
    tag: '运维技能',
  },
  {
    slug: 'image-compress-guide',
    title: '如何压缩图片不损失画质？图片压缩完全指南',
    desc: '图片压缩原理、格式对比、最佳实践，在保持画质的前提下大幅减小图片体积。',
    date: '2026-02-25',
    tag: '实用技巧',
  },
  {
    slug: 'sql-formatting-guide',
    title: 'SQL格式化最佳实践：写出可读性强的SQL语句',
    desc: 'SQL代码规范、格式化技巧、命名约定，附在线格式化工具。',
    date: '2026-02-25',
    tag: '开发知识',
  },
  {
    slug: 'ip-geolocation-guide',
    title: '如何查询IP地址的地理位置？IP定位原理详解',
    desc: 'IP地址定位原理、精度分析、隐私保护，教你查询任意IP的地理位置信息。',
    date: '2026-02-25',
    tag: '网络知识',
  },
  {
    slug: 'regex-tutorial',
    title: '正则表达式入门教程：从零开始学Regex',
    desc: '正则表达式基础语法、常用模式、实战示例，手把手教你掌握正则表达式。',
    date: '2026-02-25',
    tag: '开发技能',
  },
  {
    slug: 'base64-encoding-guide',
    title: 'Base64编码是什么？原理、用途与在线工具',
    desc: '详解Base64编码原理、为什么需要Base64、常见使用场景。',
    date: '2026-02-25',
    tag: '开发知识',
  },
  {
    slug: 'hash-algorithm-guide',
    title: 'Hash加密算法详解：MD5、SHA-1、SHA-256有什么区别？',
    desc: '详解常见Hash算法的原理、区别、安全性对比，以及实际应用场景。',
    date: '2026-02-25',
    tag: '信息安全',
  },
  {
    slug: 'jwt-token-guide',
    title: 'JWT Token详解：原理、结构与安全实践',
    desc: '详解JWT的工作原理、三段式结构、签名验证，以及安全最佳实践。',
    date: '2026-02-25',
    tag: '开发知识',
  },
  {
    slug: 'markdown-cheatsheet',
    title: 'Markdown语法速查表：5分钟掌握Markdown写作',
    desc: '最全Markdown语法速查表，涵盖标题、列表、链接、代码块、表格等常用语法。',
    date: '2026-02-26',
    tag: '效率工具',
  },
  {
    slug: 'css-color-formats',
    title: 'CSS颜色格式详解：HEX、RGB、HSL怎么选？',
    desc: '详解CSS颜色格式的区别、转换方法和使用场景。',
    date: '2026-02-26',
    tag: '前端开发',
  },
  {
    slug: 'pdf-tools-guide',
    title: 'PDF文件处理完全指南：合并、压缩、转换一站搞定',
    desc: '详解PDF常见处理需求和解决方案，附免费在线工具。',
    date: '2026-02-26',
    tag: '实用工具',
  },
  {
    slug: 'css-box-shadow-guide',
    title: 'CSS Box Shadow完全指南：从基础到高级阴影效果',
    desc: '详解box-shadow语法、参数、多层阴影、常用效果，附可视化生成器。',
    date: '2026-02-26',
    tag: '前端开发',
  },
  {
    slug: 'developer-tools-collection-2026',
    title: '2026年程序员必备在线工具合集：40+免费开发者工具',
    desc: '精选40+免费在线开发者工具，涵盖JSON、Base64、正则、PDF等，程序员必备。',
    date: '2026-02-26',
    tag: '工具合集',
  },
  {
    slug: 'url-encoding-guide',
    title: 'URL编码是什么？为什么链接里有%20？',
    desc: '详解URL编码原理、为什么需要编码、常见编码字符对照表。',
    date: '2026-02-26',
    tag: '开发知识',
  },
  {
    slug: 'timestamp-conversion-guide',
    title: 'Unix时间戳是什么？时间戳转换完全指南',
    desc: '详解Unix时间戳的概念、转换方法、各编程语言实现。',
    date: '2026-02-26',
    tag: '开发知识',
  },
  {
    slug: 'emoji-unicode-guide',
    title: 'Emoji背后的技术：Unicode编码与Emoji发展史',
    desc: '详解Emoji的Unicode编码原理、发展历史、跨平台差异。',
    date: '2026-02-26',
    tag: '技术科普',
  },
  {
    slug: 'gradient-design-tips',
    title: 'CSS渐变设计技巧：打造专业级渐变背景',
    desc: '实用CSS渐变设计技巧，包括配色原则、常见渐变模式。',
    date: '2026-02-26',
    tag: '前端设计',
  },
  {
    slug: 'seo-meta-tags-guide',
    title: 'SEO Meta标签完全指南：让搜索引擎爱上你的网站',
    desc: '详解HTML meta标签对SEO的影响，包括title、description、OG的最佳实践。',
    date: '2026-02-26',
    tag: 'SEO优化',
  },
  { slug: 'yaml-vs-json', title: 'YAML和JSON的区别：什么时候用哪个？', desc: '对比YAML和JSON的语法、优缺点和适用场景，帮你选择合适的数据格式。', date: '2026-02-26', tag: '开发知识' },
  { slug: 'linux-file-permissions', title: 'Linux文件权限详解：chmod 777到底是什么意思？', desc: '详解Linux文件权限系统，rwx权限、数字表示法、chmod命令使用方法。', date: '2026-02-26', tag: 'Linux' },
  { slug: 'http-status-codes-guide', title: 'HTTP状态码大全：200/301/404/500都是什么意思？', desc: '完整的HTTP状态码参考，包括常见状态码的含义和使用场景。', date: '2026-02-26', tag: '开发知识' },
  { slug: 'ascii-code-table', title: 'ASCII码表完整版：字符编码入门指南', desc: 'ASCII编码的历史、完整码表和在编程中的应用。', date: '2026-02-26', tag: '编码知识' },
  { slug: 'morse-code-history', title: '摩尔斯电码入门：从历史到实用转换', desc: '摩尔斯电码的发明历史、编码规则和现代应用。', date: '2026-02-26', tag: '编码知识' },
  { slug: 'binary-number-system', title: '二进制是什么？计算机为什么用二进制？', desc: '通俗易懂地解释二进制原理和计算机使用二进制的原因。', date: '2026-02-26', tag: '计算机基础' },
  { slug: 'caesar-cipher-guide', title: '凯撒密码和ROT13：最古老的加密方法', desc: '凯撒密码的历史、原理和ROT13在现代的应用。', date: '2026-02-26', tag: '密码学' },
  { slug: 'unicode-explained', title: 'Unicode编码详解：为什么emoji能在全世界通用？', desc: '从ASCII到Unicode的演进，解释字符编码的统一标准。', date: '2026-02-26', tag: '编码知识' },
  { slug: 'color-theory-basics', title: '配色理论入门：互补色、类似色、三角色是什么？', desc: '设计师必备的色彩理论基础知识和配色技巧。', date: '2026-02-26', tag: '设计知识' },
  { slug: 'web-fonts-guide', title: '网页字体完全指南：Google Fonts使用教程', desc: 'Web字体的使用方法、性能优化和Google Fonts教程。', date: '2026-02-26', tag: '前端开发' },
  { slug: 'css-grid-tutorial', title: 'CSS Grid布局教程：从入门到实战', desc: 'CSS Grid布局的完整教程，包括基本概念和实战案例。', date: '2026-02-26', tag: 'CSS教程' },
  { slug: 'css-animation-guide', title: 'CSS动画完全指南：@keyframes从零开始', desc: 'CSS动画的完整教程，从transition到@keyframes。', date: '2026-02-26', tag: 'CSS教程' },
  { slug: 'text-shadow-css', title: 'CSS text-shadow属性详解：文字阴影效果大全', desc: 'text-shadow的语法、多层阴影和创意文字效果。', date: '2026-02-26', tag: 'CSS教程' },
  { slug: 'placeholder-images-guide', title: '占位图服务大全：设计师必备的占位图工具', desc: '常用占位图服务对比和使用方法。', date: '2026-02-26', tag: '设计工具' },
  { slug: 'aspect-ratio-explained', title: '常见宽高比详解：16:9、4:3、21:9有什么区别？', desc: '屏幕和图片常见宽高比的含义和应用场景。', date: '2026-02-26', tag: '设计知识' },
  { slug: 'open-graph-protocol', title: 'Open Graph协议详解：让你的网页在社交媒体上好看', desc: 'OG标签的作用、写法和最佳实践。', date: '2026-02-26', tag: 'SEO优化' },
  { slug: 'jsonpath-tutorial', title: 'JSONPath教程：像XPath一样查询JSON数据', desc: 'JSONPath的语法和常见用法。', date: '2026-02-26', tag: '开发知识' },
  { slug: 'html-formatting-tips', title: 'HTML代码格式化最佳实践：写出整洁的HTML', desc: 'HTML代码规范和格式化技巧。', date: '2026-02-26', tag: '前端开发' },
  { slug: 'regex-common-patterns', title: '20个最常用的正则表达式：邮箱、手机号、URL验证', desc: '开发中最常用的正则表达式模式集合。', date: '2026-02-26', tag: '开发工具' },
  { slug: 'robots-txt-guide', title: 'robots.txt完全指南：控制搜索引擎爬虫', desc: 'robots.txt的语法、常见配置和SEO影响。', date: '2026-02-26', tag: 'SEO优化' },
  { slug: 'markdown-table-syntax', title: 'Markdown表格语法详解：对齐、合并、美化技巧', desc: 'Markdown表格的完整语法和高级技巧。', date: '2026-02-26', tag: '开发工具' },
  { slug: 'text-processing-tips', title: '文本批量处理技巧：查找替换的高级用法', desc: '文本批量处理的方法和工具推荐。', date: '2026-02-26', tag: '效率工具' },
  { slug: 'punycode-idn-guide', title: 'Punycode和国际化域名：中文域名是怎么工作的？', desc: 'Punycode编码原理和国际化域名的工作机制。', date: '2026-02-26', tag: '网络知识' },
  { slug: 'image-resize-guide', title: '图片尺寸调整指南：不失真缩放的技巧', desc: '图片缩放的原理和保持质量的方法。', date: '2026-02-26', tag: '图片处理' },
  { slug: 'image-filter-css', title: 'CSS滤镜效果大全：blur、grayscale、sepia等详解', desc: 'CSS filter属性的完整参考和创意用法。', date: '2026-02-26', tag: 'CSS教程' },
  { slug: 'color-picker-guide', title: '网页取色器使用指南：快速获取任意颜色值', desc: '各种取色工具的使用方法和颜色格式转换。', date: '2026-02-26', tag: '设计工具' },
  { slug: 'tip-calculator-guide', title: '小费计算指南：各国小费文化和计算方法', desc: '全球小费文化对比和实用计算技巧。', date: '2026-02-26', tag: '生活工具' },
  { slug: 'json-comparison-tools', title: 'JSON对比工具：快速找出两段JSON的差异', desc: 'JSON对比的方法和工具推荐。', date: '2026-02-26', tag: '开发工具' },
  { slug: 'json-xml-conversion', title: 'JSON和XML互转：格式转换完全指南', desc: 'JSON和XML的区别以及互转方法。', date: '2026-02-26', tag: '开发知识' },
  { slug: 'toml-config-guide', title: 'TOML配置文件格式详解：比YAML更简单的选择', desc: 'TOML格式的语法和与YAML/JSON的对比。', date: '2026-02-26', tag: '开发知识' },
  { slug: 'flexbox-vs-grid', title: 'Flexbox vs Grid：什么时候用哪个？', desc: 'CSS Flexbox和Grid布局的对比和选择指南。', date: '2026-02-26', tag: 'CSS教程' },
  { slug: 'favicon-design-guide', title: 'Favicon设计指南：让你的网站图标脱颖而出', desc: 'Favicon的设计规范、尺寸要求和制作方法。', date: '2026-02-26', tag: '设计知识' },
  { slug: 'svg-basics-tutorial', title: 'SVG入门教程：矢量图形从零开始', desc: 'SVG的基本语法、常用元素和动画效果。', date: '2026-02-26', tag: '前端开发' },
  { slug: 'css-minification-guide', title: 'CSS压缩优化：减小文件体积提升加载速度', desc: 'CSS压缩的原理、工具和最佳实践。', date: '2026-02-26', tag: '性能优化' },
  { slug: 'javascript-minification', title: 'JavaScript压缩混淆：原理和最佳实践', desc: 'JS压缩和混淆的方法、工具和注意事项。', date: '2026-02-26', tag: '性能优化' },
  { slug: 'xml-json-comparison', title: 'XML vs JSON：数据格式选择指南', desc: 'XML和JSON的详细对比和适用场景分析。', date: '2026-02-26', tag: '开发知识' },
  { slug: 'html-preview-tools', title: '在线HTML预览工具：前端开发必备', desc: '在线HTML编辑和预览工具的使用方法。', date: '2026-02-26', tag: '开发工具' },
  { slug: 'json-schema-tutorial', title: 'JSON Schema入门：数据验证的标准方法', desc: 'JSON Schema的语法和数据验证应用。', date: '2026-02-26', tag: '开发知识' },
  { slug: 'border-radius-tricks', title: 'CSS border-radius高级技巧：不只是圆角', desc: 'border-radius的高级用法和创意形状。', date: '2026-02-26', tag: 'CSS教程' },
  { slug: 'markdown-to-html-guide', title: 'Markdown转HTML：原理和常用工具', desc: 'Markdown到HTML的转换原理和工具推荐。', date: '2026-02-26', tag: '开发工具' },
  { slug: 'pdf-merge-guide', title: 'PDF合并教程：多个PDF文件合并为一个', desc: '在线和离线PDF合并的方法和工具。', date: '2026-02-26', tag: 'PDF工具' },
  { slug: 'pdf-compression-tips', title: 'PDF压缩技巧：减小PDF文件大小的5种方法', desc: 'PDF压缩的原理和实用技巧。', date: '2026-02-26', tag: 'PDF工具' },
  { slug: 'image-to-pdf-guide', title: '图片转PDF教程：批量图片合并为PDF', desc: '将多张图片转换为PDF的方法和工具。', date: '2026-02-26', tag: 'PDF工具' },
  { slug: 'tts-technology-guide', title: '文本转语音技术：TTS原理和应用场景', desc: 'TTS技术的发展历史、原理和现代应用。', date: '2026-02-26', tag: '技术科普' },
  { slug: 'ai-copywriting-tips', title: 'AI文案写作技巧：让AI帮你写出爆款文案', desc: 'AI辅助文案写作的方法和提示词技巧。', date: '2026-02-26', tag: 'AI应用' },
  { slug: 'bmi-health-guide', title: 'BMI指数怎么算？健康体重范围对照表', desc: 'BMI计算方法和健康体重标准参考。', date: '2026-02-26', tag: '健康工具' },
  { slug: 'date-calculation-tips', title: '日期计算技巧：怎么快速算两个日期之间的天数？', desc: '日期差值计算的方法和实用技巧。', date: '2026-02-26', tag: '实用技巧' },
  { slug: 'pomodoro-technique', title: '番茄工作法完全指南：提升专注力的科学方法', desc: '番茄工作法的原理、步骤和实践建议。', date: '2026-02-26', tag: '效率提升' },
  { slug: 'random-number-generation', title: '随机数生成原理：计算机如何产生随机数？', desc: '伪随机数和真随机数的区别与原理。', date: '2026-02-26', tag: '计算机基础' },
  { slug: 'unit-conversion-guide', title: '常用单位换算表：长度、重量、温度一文搞定', desc: '日常最常用的单位换算对照表。', date: '2026-02-26', tag: '实用工具' },
  { slug: 'screen-resolution-guide', title: '屏幕分辨率详解：1080p/2K/4K有什么区别？', desc: '屏幕分辨率的含义和常见规格对比。', date: '2026-02-26', tag: '技术科普' },
  { slug: 'user-agent-explained', title: 'User Agent是什么？浏览器UA字符串详解', desc: 'UA字符串的组成、用途和解析方法。', date: '2026-02-26', tag: '开发知识' },
  { slug: 'loan-interest-guide', title: '房贷计算指南：等额本息vs等额本金哪个划算？', desc: '两种还款方式的对比和选择建议。', date: '2026-02-26', tag: '金融知识' },
  { slug: 'percentage-calculation', title: '百分比计算方法大全：涨幅、折扣、占比怎么算？', desc: '各种百分比计算场景的公式和方法。', date: '2026-02-26', tag: '数学工具' },
  { slug: 'csv-data-processing', title: 'CSV文件处理指南：导入、查看、转换全攻略', desc: 'CSV文件的处理方法和常用工具。', date: '2026-02-26', tag: '数据处理' },
  { slug: 'text-sorting-techniques', title: '文本排序技巧：按字母、数字、自定义规则排序', desc: '文本排序的各种方法和工具。', date: '2026-02-26', tag: '文本处理' },
  { slug: 'text-reverse-uses', title: '文本反转的妙用：回文检测、密码生成等', desc: '文本反转的有趣应用场景。', date: '2026-02-26', tag: '文本处理' },
  { slug: 'stopwatch-timer-guide', title: '在线计时器和秒表：时间管理的好帮手', desc: '在线计时工具的使用方法和时间管理技巧。', date: '2026-02-26', tag: '效率工具' },
  { slug: 'scientific-calculator-guide', title: '在线科学计算器使用指南：三角函数、对数、幂运算', desc: '科学计算器的功能介绍和使用方法。', date: '2026-02-26', tag: '数学工具' },
  { slug: 'word-frequency-analysis', title: '词频统计分析：文本挖掘的第一步', desc: '词频分析的原理和应用场景。', date: '2026-02-26', tag: '数据分析' },
  { slug: 'qr-code-scanning', title: '二维码识别技术：从原理到实践', desc: '二维码的编码原理和识别技术。', date: '2026-02-26', tag: '技术科普' },
  { slug: 'image-watermark-guide', title: '图片加水印教程：保护你的原创图片', desc: '给图片添加水印的方法和最佳实践。', date: '2026-02-26', tag: '图片处理' },
  { slug: 'weekly-report-tips', title: '周报写作技巧：如何写出让领导满意的周报', desc: '周报写作的结构、技巧和模板。', date: '2026-02-26', tag: '职场技能' },
  { slug: 'resume-ats-guide', title: '简历ATS系统：如何让你的简历通过机器筛选', desc: 'ATS系统的工作原理和简历优化技巧。', date: '2026-02-26', tag: '求职指南' },
  { slug: 'naming-culture-china', title: '中国起名文化：从五行八字到现代取名趋势', desc: '中国传统和现代起名文化的演变。', date: '2026-02-26', tag: '文化知识' },
  { slug: 'email-etiquette-guide', title: '邮件礼仪指南：职场邮件的10个注意事项', desc: '职场邮件的礼仪规范和常见错误。', date: '2026-02-26', tag: '职场技能' },
  { slug: 'online-tools-security', title: '在线工具安全吗？如何安全使用网页工具', desc: '在线工具的安全性分析和使用建议。', date: '2026-02-26', tag: '安全知识' },
  { slug: 'developer-productivity', title: '程序员效率提升：10个节省时间的开发技巧', desc: '提升开发效率的实用技巧和工具推荐。', date: '2026-02-26', tag: '开发效率' },
  { slug: 'web-accessibility-guide', title: '网页无障碍设计指南：让所有人都能使用你的网站', desc: '网页无障碍设计的标准和实践方法。', date: '2026-02-26', tag: '前端开发' },
  { slug: 'seo-basics-2026', title: '2026 SEO入门指南：搜索引擎优化基础知识', desc: 'SEO的基本概念、技巧和2026年最新趋势。', date: '2026-02-26', tag: 'SEO优化' },
]

export default function BlogPage() {
  return (
    <main className="max-w-4xl mx-auto px-4 py-12">
      <Link href="/" className="text-sm text-blue-500 hover:underline mb-6 inline-block">← 返回工具集</Link>
      <h1 className="text-3xl font-bold text-gray-900 mb-2">📚 博客</h1>
      <p className="text-gray-500 mb-8">AI工具使用技巧、文案模板、职场干货</p>
      <div className="space-y-6">
        {posts.map(p => (
          <Link key={p.slug} href={`/blog/${p.slug}`}
            className="block p-6 bg-white rounded-xl shadow-sm hover:shadow-md transition border border-gray-100">
            <div className="flex items-center gap-3 mb-2">
              <span className="text-xs bg-blue-100 text-blue-600 px-2 py-1 rounded-full">{p.tag}</span>
              <span className="text-xs text-gray-400">{p.date}</span>
            </div>
            <h2 className="text-lg font-semibold text-gray-900 mb-1">{p.title}</h2>
            <p className="text-sm text-gray-500">{p.desc}</p>
          </Link>
        ))}
      </div>
    </main>
  )
}
